import localFont from "next/font/local";
import "./globals.css";
import { Providers } from '@/providers';
import { getServerSession } from "next-auth";
import { Toaster } from 'sonner';
import { authOptions } from "@/app/api/auth/[...nextauth]/option";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <Toaster position="bottom-right" />
        <Providers session={session}>{children}</Providers>
      </body>
    </html>
  );
}
