
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function MainLayout({ children }) {
    return (
   
          <SidebarProvider>
            <AppSidebar />
  
            {children}
          </SidebarProvider>
      
    );
  }
  