
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };
  
  export default function ClientLayout({ children }) {
    return (
   
          <SidebarProvider>
            <AppSidebar userType="employee"/>
  
            {children}
          </SidebarProvider>
      
    );
  }
  